### ISSUE TITLE
Not fully automated scripts

### ISSUE THREAD

**Issue by 99stealth** [AndrewKarpaty/helper_scripts#1]
Hi Andriy,

Nice work. But as I see in your scripts you propose user to choose Linux distro in order to install software or check health of httpd. In my opinion it will be better if scripts find out by it self in which one it was launched. In case if script doesn't know what is OS it should exit with ERROR.
Good luck

**Comment by AndrewKarpaty** [comment]
Okay , thank you. I will try to fix it

**Comment by AndrewKarpaty** [comment]
Can you check my solution again?
